### ISSUE TITLE
400 Bad Request: The browser (or proxy) sent a request that this server could not understand. KeyError: 'start'

### ISSUE THREAD

**Issue by elbination** [Sighery/mongodb-flask-datatables#4]
I have encountered a serious error "400 Bad Request: The browser (or proxy) sent a request that this server could not understand. KeyError: 'start'". I've tried to fix some code in the following section:

```
def paging(self):
        pages = {
            "start": 0,
            "length": 0
        }

        pages['start'] = int(self.request_values['start'])
        pages['length'] = int(self.request_values['length'])

        return pages
```

but nothing works. 
Can somebody help me?

**Comment by Sighery** [comment]
I'm guessing DataTables has changed its requests with a new version. I can't even remember the version I was using when I wrote this. And with a new version the schema it uses has probably changed. Some keys might have different names now and all that.

I'm sorry but I don't think I'll be working on this. I just don't have the time at the moment. Feel free to make a PR if you end up forking it and making it work for more recent versions, though.
