### ISSUE TITLE
Filter on a specific columns

### ISSUE THREAD

**Issue by uBadRequest** [Sighery/mongodb-flask-datatables#5]
Thank you for this man! I was struggling trying to add server side processing to datatables from MongoDB.

Is there a better way of creating a data grid from Mongo? I know this is like 3 years old, so I was wondering if this is still the best way to really do this? I don't want to get too deep into this project and find that I should have done this in a different way!

How would you add an option to filter on specific columns in the datatable with this implementation?

I also want to add a button to next to each row, it would just update a column in the record from true to false, it would be used as a way to mark it as "reviewed". How would you suggest to add that?

**Comment by Sighery** [comment]
Sorry, I wrote this a long time ago. I know for a fact that the newer DataTables versions use a different API that is not compatible with this code. MongoDB might have changed too.

This project seems more recent, so you might have better luck there https://github.com/pauljolsen/mongo-datatables.

Maybe using something like GraphQL is a better option for your needs https://github.com/arisgk/data-table

I'll archive this repository now. The code as it is won't work (unless you happen to be using some ancient DataTables version), so archiving it doesn't give folks the wrong impression.
